services:
  database:
    image: 'postgres:15.0'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
